Update retroarch-1.8.2.ebuild
Dependency net-libs/mbedtls changed to <net-libs/mbedtls-2.18.1
With higher versions it would faild saying
"libretro-common/net/net_socket_ssl.c:128:50: error: ‘struct ssl_state’ has no member named ‘ca’
  128 |    mbedtls_ssl_conf_ca_chain(&state->conf, &state->ca, NULL);"